name: Playwright Tests

on:
  push:
    branches: [ main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest #macos-latest, window-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    
    strategy:
      matrix:
        browser: [chromium]
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.browser }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.browser }}
        path: playwright-report/
        retention-days: 30
    
    - name: Upload test results JSON
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.browser }}
        path: test-results.json
        retention-days: 30

